# Generated by Django 4.0.3 on 2022-03-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_annotation_xmlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('imageurl', models.URLField()),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
        ),
    ]
