# Generated by Django 4.0.3 on 2022-03-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_onepiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
