# Generated by Django 4.0.3 on 2022-03-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Onepiece',
        ),
    ]
