# Generated by Django 4.0.3 on 2022-03-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_delete_onepiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xml_img_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_file_name', models.FileField(upload_to='xml')),
                ('img_file_name', models.FileField(upload_to='source_img')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
    ]
