# Generated by Django 4.0.3 on 2022-03-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_xml_img_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='xmin',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='image',
            name='xmlfile',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
