# Generated by Django 4.0.3 on 2022-04-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_xml_img_files_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='xml_img_files',
            name='user',
        ),
    ]
