# Generated by Django 4.0.4 on 2022-04-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_remove_category_user_remove_xml_img_files_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='oimg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
