# Generated by Django 4.0.4 on 2022-04-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_image_oimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cropped',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
